fail_fast: false
exclude: |
    (?x)^(
        tests/data/.*
    )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: uv run isort .
        language: system
        pass_filenames: false
  - repo: local
    hooks:
    -   id: pyupgrade
        name: pyupgrade
        entry: uv run pyupgrade --py36-plus
        language: python
        types: [python]
        pass_filenames: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: uv run flake8 .
        language: system
        pass_filenames: false