[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "peeringdb"
version = "2.1.1"
description = "PeeringDB Django models"
readme = "README.md"
repository = "https://github.com/peeringdb/peeringdb-py"
authors = [ "PeeringDB <support@peeringdb.com>",]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Intended Audience :: Telecommunications Industry",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet"
]
[[tool.poetry.packages]]
include = "peeringdb"
from = "src"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.poetry.scripts]
peeringdb = "peeringdb.cli:main"

[tool.poetry.dependencies]
python = "^3.9"
confu = "^1"
munge = { extras = ["toml", "tomlkit", "yaml"], version = "^1.2.0" }
"twentyc.rpc" = "^1"
pyyaml = "^6.0.1"
httpx = ">=0.24.1"
setuptools = "^74.1.2"

[tool.poetry.dev-dependencies]

# testing
django_peeringdb = "^3.1.0"
django = "~4.2"

pytest = ">=8"
pytest-cov = "*"
tox = ">=4"

# linting
black = ">=24"
isort = "^5.13.2"
flake8 = ">=7"
mypy = "^1.11.2"
pre-commit = "^3.8"
pyupgrade = "^3.17"

# docs
markdown = "*"
markdown-include = ">=0.5,<1"
mkdocs = "^1.6.1"

# ctl
ctl = "^1"
jinja2 = "^3"
tmpl = "^1"
twine = "^5.1.1"

[tool.poetry.plugins."markdown.extensions"]
pymdgen = "pymdgen.md:Extension"
